name: huawei_all_health
description: provider Health Kit & HiHealthKit impl.
homepage: https://github.com/IAMSUPERMONKEY/huawei_all_health
repository: https://github.com/IAMSUPERMONKEY/huawei_all_health

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.supermonkey.hms.flutter.health
        pluginClass: HealthPlugin
